# [Zaib's AI Notebook](https://github.com/zaibgray/numpy) | NumPy

## Overview

- NumPy is a Python library used to work with numbers and arrays.
- It's fast, so it's used a lot in data science.

## Arrays

- A NumPy array (`ndarray`) stores values of the **same type only**. A normal Python list can mix types, but a NumPy array can't.
- Create one using `np.array()`: `np.array([1, 2, 3])`

### Rank & Shape

- **Rank** = how many dimensions the array has.
  - `[1, 2, 3]` → rank 1 (flat list)
  - `[[1, 2, 3], [4, 5, 6]]` → rank 2 (like a table)
- **Shape** = the size of each dimension, written as a tuple.
  - `(3,)` → 1D array with 3 items
  - `(2, 3)` → 2D array with 2 rows and 3 columns

### Accessing & Modifying

- Use `[]` to get values from an array.
  - 1D: `a[0]`
  - 2D: `c[row, column]`
- Arrays can be changed after creation: `a[0] = 5`

In [27]:
import numpy as np

In [28]:
a = np.array([1, 2, 3])         # creating ndarray(N-dimensional array)

print(a)
print(type(a))                  # ndarray
print(a.shape)                  # (3,) 
print(a[0], a[1], a[2])         # 1, 2, 3

a[2] = 4                        # changing element of the array
print(a)                        # [1 2 4]

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1 2 3
[1 2 4]


In [29]:
# number of starting [ brackets = number of dimensions.
b = np.array([[1, 2, 3], [4, 5, 6]])                                    # creating 2D array
print(b.shape)                                                          # 2 rows and 3 columns (2,3)
print(b.ndim)
print(b[0,0], b[0,1], b[0,2])                                           # accessing 2d array

c = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])                       # creating 3D array
print(c.shape)                                                          # 1 3D array, 3 rows and 3 columns (1,3,3)
print(c.ndim)

print(c[0,2,2], c[0,2,1], c[0,2,0],)                                    # accessing 3d array
len(c.shape) == c.ndim

(2, 3)
2
1 2 3
(1, 3, 3)
3
9 8 7


True

In [30]:
d = np.array((1, 2, 3))             #creating ndarray using tuple
print(d)
print(d.shape)
print(type(d))

e = np.array(((1, 2, 3), (4, 5, 6)))
print(e)

# NumPy arrays can also made by other Numpy arrays and lists
# but their data type always be NumPy ndarray

[1 2 3]
(3,)
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [31]:
# making ndarray by using Python list
list = [1, 2, 3, 4, 5]
a = np.array(list)
print(a, type(a), a.shape, a.ndim)

#making NumPy array using other NumPy arrays or/and list
b = np.array([a, a, a])
print(b, type(b), b.shape, b.ndim)

c = np.array([list, list, list])
print(c, type(c), c.shape, c.ndim)

d = np.array([a, list, a])
print(d, type(d), d.shape, d.ndim)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,) 1
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]] <class 'numpy.ndarray'> (3, 5) 2
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]] <class 'numpy.ndarray'> (3, 5) 2
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]] <class 'numpy.ndarray'> (3, 5) 2


- Every row must have the same number of items, or could get unexpected results.

In [32]:
p = np.array([[1,2], [3, 4]])
print(p * 2)

# p = np.array([[1], [3, 4]])
# print(p * 2)
# will get error

q = np.array([[1, 2, 4], [3, 4, 5], [5, 6, 7]])
print(q * 3)

[[2 4]
 [6 8]]
[[ 3  6 12]
 [ 9 12 15]
 [15 18 21]]


# Creating NumPy arrays using **NumPy functions**
- np.zeros()    -> all zero
- np.ones()     -> all one
- np.empty()    -> empty array
- np.arrange()  -> used to make any Dimension of array
- np.linspace() -> linearly spaced array
- np.eye()      -> identity matrix
- np.random

In [33]:
# creating 1D/2D/3D array of 0's
z1 = np.zeros(3)
print(z1)
z2 = np.zeros([2, 4])
print(z2)
z3 = np.zeros([1, 4, 4])
print(z3)

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [34]:
# creating 1D/2D/3D array of 1's
o1 = np.ones(3)
print(o1)
o2 = np.ones([2, 4])
print(o2)
o3 = np.ones([1, 4, 4])
print(o3)

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [35]:
# creating 1D/2D/3D emtpy array
e1 = np.empty(2)                    # Creates a placeholder array to fill with values later
e2 = np.empty([2, 2])
e3 = np.empty([1, 3, 3])
print(e3)

e1[0] = 1
e1[1] = 2
print(e1)

e2[0,0] = 1
e2[0,1] = 1
e2[1,0] = 1
e2[1,1] = 1
print(e2)

[[[1.48e-323 2.96e-323 5.93e-323]
  [4.45e-323 5.93e-323 7.41e-323]
  [7.41e-323 8.89e-323 1.04e-322]]]
[1. 2.]
[[1. 1.]
 [1. 1.]]


In [36]:
# creating array using arange
r = np.arange(10)
print(r)

# first number, last number, and the step size (2, 9, 2)
r1 = np.arange(2, 9, 2)
print(r1, type(r1))

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8] <class 'numpy.ndarray'>


In [37]:
#creating 2D array using reshape
r2 = np.arange(2, 14).reshape(3, 4)         
# 13 - 1 = 12, so  3*4 = 12 or 6*2 = 12
# use this method to make 2D or 3D array
print(r2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [38]:
#creating 3D array using reshape
r3 = np.arange(1, 10).reshape(1, 3, 3)
print(r3)

r4 = np.arange(4, 52).reshape(3, 4, 4)
# 52 - 4 = 48
# 48's prime factorization is 2*2*2*2*3
print(r4)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]
  [48 49 50 51]]]


In [39]:
#making array using linspace
#step size = (stop - start) / num - 1
lp1 = np.linspace(1, 10, num=4)
print(lp1)

[ 1.  4.  7. 10.]


In [40]:
# creating array using eye
e = np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [41]:
# creating array using random
# it genrate random number between 0 and 1
rd = np.random.random(10)
print(rd)

r = np.round(rd * 100)
np.array(r, dtype=int)

[0.69534681 0.8318866  0.33584551 0.21307149 0.33629091 0.39893085
 0.96811071 0.00401146 0.21386647 0.87159171]


array([70, 83, 34, 21, 34, 40, 97,  0, 21, 87])

In [42]:
# creating 2D array using random 
rd2 = np.random.random([2,3])
print(rd2)

r = np.round(rd2 * 100)
arr = np.array(r, dtype=int)
print(arr)

#appling scaler muliplication
print(arr * 2)

# to keep the random output same we can use
# Best practice setup
rng = np.random.default_rng(seed=100)

# 1. Most used for integers
dice_rolls = rng.integers(1, 7, size=5) 
print(dice_rolls)

# 2. Most used for floats
percentages = rng.random(size=5)
print(percentages)

# 3. Most used for statistical distributions
bell_curve = rng.normal(loc=0, scale=1, size=5)
print(bell_curve)

[[0.11724934 0.98389895 0.80550032]
 [0.71132691 0.7247461  0.92407092]]
[[12 98 81]
 [71 72 92]]
[[ 24 196 162]
 [142 144 184]]
[5 6 1 4 1]
[0.04295157 0.9736544  0.5964717  0.79026316 0.91033938]
[ 0.7450626   1.10434724  2.2429724  -0.61149312  0.04721118]


# Array Indexing

### 1. Basic Indexing (Pick One Element)
Use exact positions to grab a single item. Counting starts at 0. Negative numbers count backward from the end.
- arr[0] → First item
- arr[-1] → Last item
- arr[1, 2] → Item at Row 1, Column 2

### 2. Slicing (Pick a Range)
Use a colon : to grab a continuous chunk. The syntax is [start:stop]. The stop position is not included.
- arr[1:4] → Items at positions 1, 2, and 3
- arr[2:] → Everything from position 2 to the end
- arr[:, 1] → All rows, but only Column 1

### 3. Fancy Indexing (Pick Specific Items)
Pass a list of numbers inside the brackets to grab items that are not next to each other.
- arr[[0, 3, 5]] → Grabs items at positions 0, 3, and 5

### 4. Boolean Indexing (Pick by Condition)
Filter your data using math conditions (like >, <, or ==).
- arr[arr > 5] → Grabs only the numbers greater than 5
- arr[arr < 0] = 0 → Finds all negative numbers and changes them to 0
### 5. Structural Indexing (Change the Shape)
Add an extra dimension to your array on the fly.
- arr[:, np.newaxis] → Turns a flat row array into a vertical column array

### One Crucial Rule
- Slicing creates a link to the original array. If you modify the slice, the original array changes too.
- Fancy and Boolean indexing create a brand new copy. Modifying the result does not affect the original array.

In [43]:
# Basic Indexing
import numpy as np
arr = np.arange(1,90)
print(arr[0])
print(arr[9])
print(arr[80])
print(arr[88])

1
10
81
89


In [44]:
# Slicing (Pick a Range)
import numpy as np
arr1 = np.arange(10)
print(arr[1])

arr2 = np.arange(1,13).reshape(3,4)
print("\n", arr2)
print(arr2[0, 1])                      #first row and second column
print(arr2[2, 3])
print(arr2[::2, ::2])


arr3 = np.arange(1,13).reshape(3,2,2)
print("\n", arr3)
print(arr3[0, 0, 0])                   #firt = what matrix, second = row, third = column
print(arr3[2, 1, 0])


arr4 = np.arange(27).reshape(3,3,3)
print("\n", arr4)
print(arr4[0, 1])
print(arr4[2, 1, 0])
print(arr4[::2, 0, ::2])

2

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
12
[[ 1  3]
 [ 9 11]]

 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
1
11

 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[3 4 5]
21
[[ 0  2]
 [18 20]]


In [45]:
# Fancy Indexing (Pick Specific Items)
import numpy as np
arr = np.arange(24).reshape(6,4)
print(arr)
print()
print(arr[[0,3,3,5]])                       # [[rows], [columns]]
print()
print(arr[[0,1], [0, 1]])                   # will get [0, 5]
# use this [0:2, 0:2] to get [[0 1][4 5]]
print()
print(arr[0:2, 0:2])                        # will get [0, 5]
print()
print(arr[:, [1, 2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[ 0  1  2  3]
 [12 13 14 15]
 [12 13 14 15]
 [20 21 22 23]]

[0 5]

[[0 1]
 [4 5]]

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]]


In [46]:
import numpy as np
arr = np.arange(27).reshape(3, 3, 3)
print(arr)
print()
print(arr[[0,1,2], [0], [2]])                   # first = matrix , second = row, third = column
print()
print(arr[[1,2], [0,2]])                        # 1st matrix's first row, 2nd matrix's third row

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[ 2 11 20]

[[ 9 10 11]
 [24 25 26]]


In [47]:
# Boolean Indexing (Pick by Condition)
import numpy as np
a = np.random.randint(1, 100, 24).reshape(6, 4)
print(a[a % 2 == 0])
print(a [(a > 50) & (a % 2 == 0) ])
print(a [~(a % 7 == 0)])

[42 10 28 18 26 16 46 16 54 96 18 98 32  6]
[54 96 98]
[87 10 18 26 16 46 16 61 54 71 73 96 89 18  5  5 32  6]


In [48]:
# Structural Indexing (Change the Shape)
import numpy as np
arr = np.array([10, 20, 30])
print("Original Shape:", arr.shape)  # Output: (3,)
print(arr)
print("-" * 20)

# 1. Convert to a Row Vector (1 row, 3 columns)
row_vec = arr[np.newaxis, :]
print("Row Vector Shape:", row_vec.shape)  # Output: (1, 3)
print(row_vec)
print("-" * 20)

# 2. Convert to a Column Vector (3 rows, 1 column) using 'None'
col_vec = arr[:, None]
print("Column Vector Shape:", col_vec.shape)  # Output: (3, 1)
print(col_vec)

Original Shape: (3,)
[10 20 30]
--------------------
Row Vector Shape: (1, 3)
[[10 20 30]]
--------------------
Column Vector Shape: (3, 1)
[[10]
 [20]
 [30]]


# Datatypes

In [49]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a, a.dtype)                   #int64

b = np.array([1.0, 2.0, 3.0, 4.0])
print(b, b.dtype)                   #flot64

c = np.array([1, 2, 3, 4], dtype=np.int8)
print(c, c.dtype)                   #int8

# type casting is very useful when it is needed to use less memory

[1 2 3 4] int64
[1. 2. 3. 4.] float64
[1 2 3 4] int8


# Math functions in NumPy

- NumPy provides many functions for manipulating arrays; you can find an exhaustive list in the [NumPy documentation](http://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html). Some common ones are listed below.

### Element-wise operations

- Algebraic operations such as `+`, `-`, `*`, `/` etc. are available both as operator overloads and as functions in the NumPy module. These operators carry out **element-wise** operations on NumPy arrays:

In [50]:
import numpy as np

x = np.arange(1, 5, dtype=np.float64).reshape(2, 2)
y = np.arange(5, 9, dtype=np.float64).reshape(2, 2)
print(x)
print(y)
print("*" * 30)

print(np.add(x, y))
print("*" * 30)

print(np.subtract(x,y))
print("*" * 30)

print(np.multiply(x,y))
print("*" * 30)

print(np.divide(x,y))
print("*" * 30)

print(np.sqrt(y))
print("*" * 30)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
******************************
[[ 6.  8.]
 [10. 12.]]
******************************
[[-4. -4.]
 [-4. -4.]]
******************************
[[ 5. 12.]
 [21. 32.]]
******************************
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
******************************
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]
******************************


## Changning Datatype

In [51]:
# astype
import numpy as np

arr = np.arange(24.0).reshape(6,4)
print(arr.dtype)                    #float64

arr.astype(np.int8)

float64


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]], dtype=int8)

## Array Operations
- Scaler Operations
- Vector Operations

In [52]:
import numpy as np

x = np.arange(12).reshape(3,4)
y = np.arange(12, 24).reshape(3,4)

In [53]:
# Scaler Operations
# arithmetic = *, /, -, +, **, //
print(x ** 2)
# relational = >, <, >=, <=, ==
print(x == y)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[False False False False]
 [False False False False]
 [False False False False]]


In [54]:
# Vector Operations 
# arithmetic
print(x-y)
print(x**y)
print(x+y)

[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


# Array Functions
- Max/Min/Sum/Prod 
- Mean, Median, Standard Deviation, Variance
- Arrays Dot Product
- Round, Floor, Ceil

In [55]:
# max/min/sum/prod
import numpy as np

arr = np.arange(27).reshape(3,3,3)
print(arr)
print("*" * 30)

print(np.max(arr))
print("*" * 30)

print(np.min(arr))
print("*" * 30)

print(np.sum(arr))
print("*" * 30)

print( np.prod(arr))
print("*" * 30)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
******************************
26
******************************
0
******************************
351
******************************
0
******************************


In [56]:
# mean/median/std/var
import numpy as np

arr = np.arange(27).reshape(3,3,3)
print(arr)
print("*" * 30)

print(np.mean(arr))
print("*" * 30)

print(np.median(arr))
print("*" * 30)

print(np.std(arr))
print("*" * 30)

print( np.var(arr))
print("*" * 30)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
******************************
13.0
******************************
13.0
******************************
7.788880963698615
******************************
60.666666666666664
******************************


# Columns of the first matrix must match rows of the second matrix.

![alt text](images/dot_product.jpg)

![alt text](images/dp_exp.jpg)

In [58]:
# arrays dot product -> the most important thing to learn
import numpy as np

x = np.arange(16).reshape(4,4)
y = np.arange(16).reshape(4,4)
# x's columns = 4, and y's rows = 4
# so can take dot product

np.dot(x,y)


array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362],
       [344, 398, 452, 506]])

In [59]:
#round/floor/ceil
import numpy as np
arr = [3.1, 3.5, 3.9, -2.3, -2.7, 5.0]
rd = np.round(np.array(arr))
fl = np.floor(np.array(arr))
cl = np.ceil(np.array(arr))

print(rd)
print(fl)
print(cl)


[ 3.  4.  4. -2. -3.  5.]
[ 3.  3.  3. -3. -3.  5.]
[ 4.  4.  4. -2. -2.  5.]


# Reshaping Array
- reshape
- transpose
- ravel

In [ ]:
# reshape change array into N-Dimentions
import numpy as np
arr = np.arange(12)
print(arr)              # simple array
print("*" * 30)

# using reshape
rarr = arr.reshape(3,4)
print(rarr)             # 2D array

# also make N-D array

[ 0  1  2  3  4  5  6  7  8  9 10 11]
******************************
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [69]:
# ravel makes any N-D array into 1D array
import numpy as np
arr = np.arange(27).reshape(3,3,3)
print(arr)
print("*" * 30)
oarr = arr.ravel()
print(oarr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
******************************
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [67]:
# trasnpose
# it changes columns into rows and rows into columns

import numpy as np
arr = np.arange(16).reshape(4,4)
print("Before Transpose")
print(arr)
print("*" * 30)
tarr = np.transpose(arr)
print("After Transpose")
print(tarr)
print("*" * 30)

Before Transpose
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
******************************
After Transpose
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
******************************


# Stacking and Splitting

### Stacking
- horizontal Stacking
- vertical Stacking

![alt text](images/hstack_vstack.png)

![alt text](images/hstack_colstack.png)

![alt text](images/2vecs.png)
### Splitting
- horizontal Stacking
- vertical Stacking

![alt text](images/splitting.png)

In [1]:
import numpy as np
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(3,4)

print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
# Stacking # shape must be same
# horizontal stacing
harr = np.hstack((a,b,a,a,b))
print(harr)
print("*"*30)
# vertical stacking
varr = np.vstack((a,b,a,a,b))
print(varr)

[[ 0  1  2  3  0  1  2  3  0  1  2  3  0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7  4  5  6  7  4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11  8  9 10 11  8  9 10 11  8  9 10 11]]
******************************
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
# splitting
a = np.arange(16).reshape(4, 4)
print(a)
print("*" * 30)

print(np.hsplit(a,2))
print("*" * 30)
print(np.vsplit(a,2))



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
******************************
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
******************************
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# **Broadcasting** (Very Important)
- **What it is:** A way to do math between arrays of different sizes without using loops. NumPy makes the smaller array "grow" to match the bigger one.

- **Why use it:** It saves memory and makes your computer run code much faster. It is perfect for things like adding a bonus score to a list of student grades.

## Broadcasting Rules

1. **Make the two arrays have the same number of dimensions**
    - If the numbers of dimesion of the two arrays are different, add new dimensions with size 1 to head of the array with the smaller dimension.
    - **Example:**
        - (3, 2) and (3,) --> now add 1, so (3, 2) and (1, 3)
        - (3, 3, 3) and (3,) --> now add 1, so (3, 3, 3) and (1, 1, 3)

2. **Make each dimesion of the two arrays the same size.**
    - If the sizes of each dimesion of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
    - **Example**
        - from 1st rule (3, 2) and (1, 3), now stretch 1 to the other array dimension, which is 3 so, (3, 3) AND (3, 3)
        
    - If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

![alt text](images/broadcasting.png)

In [7]:
# same shape
import numpy as np

a = np.arange(6).reshape(2,3)
b = np.arange(6).reshape(2,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[[ 0  2  4]
 [ 6  8 10]]


In [6]:
# diff shape
import numpy as np

a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


# **More Examples**

In [ ]:
import numpy as np

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)
print("*" * 30)

# 1st rule = (4, 3) and (3,) -> (4, 3) and (1, 3)
# 2nd rule = (4, 3) and (1, 3) -> (4, 3) and (4, 3)

print(a+b)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
******************************
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:
import numpy as np

a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)
print("*" * 30)

# 1st rule = (3, 4) and (3,) -> (3, 4) and (1, 3)
# 2nd rule = (3, 4) and (1, 3) -> (3, 4) and (3, 3)
# 3rd rule = (3,4) is not equal to (3, 3)
# So we cannot do broadcasting on these arrays

print(a+b)
# You will get erorr


In [13]:
import numpy as np

a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)
print("*" * 30)

# 1st rule = (1, 3) and (3, 1)
# 2nd rule increse 1 = (3, 3) and (3, 3), now they are same

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
******************************
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
import numpy as np

a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)
print("*" * 30)

#(1, 3) and (4, 1) --> (4, 3) and ( 4, 3)
# (x , y) and (x, y)
# first array's x = 1, increase it to second array's x = 4, so it will be (4, 3)
# second array's y = 1, increase it to first array's y = 4, so it will be (4, 3)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
******************************
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [15]:
import numpy as np

a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)
print("*" * 30)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
******************************
