# [Zaib's AI Notebook](https://github.com/zaibgray/numpy) | NumPy

## Overview

- NumPy is a Python library used to work with numbers and arrays.
- It's fast, so it's used a lot in data science.

## Arrays

- A NumPy array (`ndarray`) stores values of the **same type only**. A normal Python list can mix types, but a NumPy array can't.
- Create one using `np.array()`: `np.array([1, 2, 3])`

### Rank & Shape

- **Rank** = how many dimensions the array has.
  - `[1, 2, 3]` → rank 1 (flat list)
  - `[[1, 2, 3], [4, 5, 6]]` → rank 2 (like a table)
- **Shape** = the size of each dimension, written as a tuple.
  - `(3,)` → 1D array with 3 items
  - `(2, 3)` → 2D array with 2 rows and 3 columns

### Accessing & Modifying

- Use `[]` to get values from an array.
  - 1D: `a[0]`
  - 2D: `c[row, column]`
- Arrays can be changed after creation: `a[0] = 5`

In [1]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])         # creating ndarray(N-dimensional array)

print(a)
print(type(a))                  # ndarray
print(a.shape)                  # (3,) 
print(a[0], a[1], a[2])         # 1, 2, 3

a[2] = 4                        # changing element of the array
print(a)                        # [1 2 4]

In [ ]:
# number of starting [ brackets = number of dimensions.
b = np.array([[1, 2, 3], [4, 5, 6]])                                    # creating 2D array
print(b.shape)                                                          # 2 rows and 3 columns (2,3)
print(b.ndim)
print(b[0,0], b[0,1], b[0,2])                                           # accessing 2d array

c = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])                       # creating 3D array
print(c.shape)                                                          # 1 3D array, 3 rows and 3 columns (1,3,3)
print(c.ndim)

print(c[0,2,2], c[0,2,1], c[0,2,0],)                                    # accessing 3d array
len(c.shape) == c.ndim

In [ ]:
d = np.array((1, 2, 3))             #creating ndarray using tuple
print(d)
print(d.shape)
print(type(d))

e = np.array(((1, 2, 3), (4, 5, 6)))
print(e)

# NumPy arrays can also made by other Numpy arrays and lists
# but their data type always be NumPy ndarray

In [ ]:
# making ndarray by using Python list
list = [1, 2, 3, 4, 5]
a = np.array(list)
print(a, type(a), a.shape, a.ndim)

#making NumPy array using other NumPy arrays or/and list
b = np.array([a, a, a])
print(b, type(b), b.shape, b.ndim)

c = np.array([list, list, list])
print(c, type(c), c.shape, c.ndim)

d = np.array([a, list, a])
print(d, type(d), d.shape, d.ndim)

- Every row must have the same number of items, or could get unexpected results.

In [ ]:
p = np.array([[1,2], [3, 4]])
print(p * 2)

# p = np.array([[1], [3, 4]])
# print(p * 2)
# will get error

q = np.array([[1, 2, 4], [3, 4, 5], [5, 6, 7]])
print(q * 3)

# Creating NumPy arrays using **NumPy functions**
- np.zeros()    -> all zero
- np.ones()     -> all one
- np.empty()    -> empty array
- np.arrange()  -> used to make any Dimension of array
- np.linspace() -> linearly spaced array
- np.eye()      -> identity matrix
- np.random

In [ ]:
# creating 1D/2D/3D array of 0's
z1 = np.zeros(3)
print(z1)
z2 = np.zeros([2, 4])
print(z2)
z3 = np.zeros([1, 4, 4])
print(z3)

In [ ]:
# creating 1D/2D/3D array of 1's
o1 = np.ones(3)
print(o1)
o2 = np.ones([2, 4])
print(o2)
o3 = np.ones([1, 4, 4])
print(o3)

In [ ]:
# creating 1D/2D/3D emtpy array
e1 = np.empty(2)                    # Creates a placeholder array to fill with values later
e2 = np.empty([2, 2])
e3 = np.empty([1, 3, 3])
print(e3)

e1[0] = 1
e1[1] = 2
print(e1)

e2[0,0] = 1
e2[0,1] = 1
e2[1,0] = 1
e2[1,1] = 1
print(e2)

In [3]:
# creating array using arange
r = np.arange(10)
print(r)

# first number, last number, and the step size (2, 9, 2)
r1 = np.arange(2, 9, 2)
print(r1, type(r1))

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8] <class 'numpy.ndarray'>


In [ ]:
#creating 2D array using reshape
r2 = np.arange(2, 14).reshape(3, 4)         
# 13 - 1 = 12, so  3*4 = 12 or 6*2 = 12
# use this method to make 2D or 3D array
print(r2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [ ]:
#creating 3D array using reshape
r3 = np.arange(1, 10).reshape(1, 3, 3)
print(r3)

r4 = np.arange(4, 52).reshape(3, 4, 4)
# 52 - 4 = 48
# 48's prime factorization is 2*2*2*2*3
print(r4)

In [18]:
#making array using linspace
#step size = (stop - start) / num - 1
lp1 = np.linspace(1, 10, num=4)
print(lp1)

[ 1.  4.  7. 10.]


In [19]:
# creating array using eye
e = np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
# creating array using random
# it genrate random number between 0 and 1
rd = np.random.random(10)
print(rd)

r = np.round(rd * 100)
np.array(r, dtype=int)

[0.86865008 0.66441197 0.3721014  0.42551256 0.50616081 0.61084917
 0.97202771 0.44652542 0.13774195 0.62098769]


array([87, 66, 37, 43, 51, 61, 97, 45, 14, 62])

In [66]:
# creating 2D array using random 
rd2 = np.random.random([2,3])
print(rd2)

r = np.round(rd2 * 100)
arr = np.array(r, dtype=int)
print(arr)

#appling scaler muliplication
print(arr * 2)

# to keep the random output same we can use
# Best practice setup
rng = np.random.default_rng(seed=100)

# 1. Most used for integers
dice_rolls = rng.integers(1, 7, size=5) 
print(dice_rolls)

# 2. Most used for floats
percentages = rng.random(size=5) 

# 3. Most used for statistical distributions
bell_curve = rng.normal(loc=0, scale=1, size=5) 

[[0.17824217 0.35431049 0.09906658]
 [0.36958532 0.92413439 0.0389432 ]]
[[18 35 10]
 [37 92  4]]
[[ 36  70  20]
 [ 74 184   8]]
[5 6 1 4 1]
